django_school/apps/grades/urls.py
from django.urls import include, path

from django_school.apps.grades.views import (ClassGradesView,
                                             GradeCategoryDeleteView,
                                             GradeCategoryDetailView,
                                             GradeCategoryFormTemplateView,
                                             GradeCategoryUpdateView,
                                             GradeCreateView, GradeDeleteView,
                                             GradeUpdateView,
                                             StudentGradesView,
                                             grade_bulk_create_view,
                                             grade_categories_view)

app_name = "grades"

categories_urlpatterns = [
    path("htmx/form/", GradeCategoryFormTemplateView.as_view(), name="form"),
    path("htmx/<int:pk>/", GradeCategoryDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", GradeCategoryDeleteView.as_view(), name="delete"),
    path(
        "htmx/<int:pk>/update/",
        GradeCategoryUpdateView.as_view(),
        name="update",
    ),
    path(
        "<slug:class_slug>/<slug:subject_slug>/",
        grade_categories_view,
        name="create",
    ),
]

urlpatterns = [
    path(
        "categories/",
        include(
            (categories_urlpatterns, "categories"),
            namespace="categories",
        ),
    ),
    path(
        "student/<slug:student_slug>",
        StudentGradesView.as_view(),
        name="student_grades",
    ),
    path(
        "<slug:class_slug>/<slug:subject_slug>/add/",
        GradeCreateView.as_view(),
        name="add",
    ),
    path(
        "<int:category_pk>/add_in_bulk/",
        grade_bulk_create_view,
        name="add_in_bulk",
    ),
    path("update/<int:grade_pk>/", GradeUpdateView.as_view(), name="update"),
    path("delete/<int:grade_pk>/", GradeDeleteView.as_view(), name="delete"),
    path(
        "<slug:class_slug>/<slug:subject_slug>/",
        ClassGradesView.as_view(),
        name="class_grades",
    ),
]

django_school/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django_school.apps.common.views import attached_file_delete_view, index

urlpatterns = [
    path("", index, name="index"),
    path("users/", include("django_school.apps.users.urls", namespace="users")),
    path("classes/", include("django_school.apps.classes.urls", namespace="classes")),
    path("lessons/", include("django_school.apps.lessons.urls", namespace="lessons")),
    path("grades/", include("django_school.apps.grades.urls", namespace="grades")),
    path(
        "messages/", include("django_school.apps.messages.urls", namespace="messages")
    ),
    path("events/", include("django_school.apps.events.urls", namespace="events")),
    path("admin/", admin.site.urls),
    path("martor/", include("martor.urls")),
    path(
        "attached_files/<int:pk>/delete/",
        attached_file_delete_view,
        name="attached_file_delete",
    ),
    path("__debug__", include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/apps/grades/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse

from django_school.apps.classes.models import Class
from django_school.apps.lessons.models import Lesson, Subject


class GradeCategory(models.Model):
    name = models.CharField(max_length=64)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, related_name="grades_categories"
    )
    school_class = models.ForeignKey(
        Class, on_delete=models.CASCADE, related_name="grades_categories"
    )

    class Meta:
        verbose_name_plural = "grade categories"

    def __str__(self):
        return self.name

    @property
    def detail_url(self):
        return reverse("grades:categories:detail", args=[self.pk])

    @property
    def update_url(self):
        return reverse("grades:categories:update", args=[self.pk])

    @property
    def delete_url(self):
        return reverse("grades:categories:delete", args=[self.pk])

    @property
    def bulk_grade_creation_url(self):
        return reverse("grades:add_in_bulk", args=[self.pk])


class Grade(models.Model):
    GRADES = [
        (1.0, "1"),
        (1.5, "1+"),
        (1.75, "2-"),
        (2.0, "2"),
        (2.5, "2+"),
        (2.75, "3-"),
        (3.0, "3"),
        (3.5, "3+"),
        (3.75, "4-"),
        (4.0, "4"),
        (4.5, "4+"),
        (4.75, "5-"),
        (5.0, "5"),
        (5.5, "5+"),
        (5.75, "6-"),
        (6.0, "6"),
    ]

    grade = models.FloatField(choices=GRADES)
    weight = models.PositiveIntegerField()
    comment = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    seen_by_student = models.BooleanField(default=False)
    seen_by_parent = models.BooleanField(default=False)
    category = models.ForeignKey(
        GradeCategory, on_delete=models.CASCADE, related_name="grades"
    )
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, related_name="grades"
    )
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="grades_gotten"
    )
    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="grades_added",
    )

    def __str__(self):
        return f"{self.student}: {self.subject} - {self.grade}"

    def clean(self):
        super().clean()

        if (
            Grade.objects.filter(category=self.category, student=self.student)
            .exclude(pk=self.pk)
            .exists()
        ):
            raise ValidationError(
                "The student already has got a grade in this category."
            )

        if not self.teacher.is_teacher:
            raise ValidationError("The teacher is a teacher.")

        if not self.student.is_student:
            raise ValidationError("The student is not a student")

        if not Lesson.objects.filter(
            school_class=self.student.school_class, subject=self.subject
        ).exists():
            raise ValidationError("The student is not learning the given subject")

        if self.category.subject != self.subject:
            raise ValidationError("The grade category is not a category of the subject")

    @property
    def update_url(self):
        return reverse("grades:update", args=[self.pk])

    @property
    def delete_url(self):
        return reverse("grades:delete", args=[self.pk])

django_school/apps/grades/views.py
from collections import defaultdict

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import (CreateView, DeleteView, DetailView,
                                  TemplateView, UpdateView)

from django_school.apps.classes.models import Class
from django_school.apps.common.utils import (
    AjaxRequiredMixin, GetObjectCacheMixin, RolesRequiredMixin,
    SubjectAndSchoolClassRelatedMixin,
    does_the_teacher_teach_the_subject_to_the_class, roles_required)
from django_school.apps.grades.forms import (BulkGradeCreationCommonInfoForm,
                                             BulkGradeCreationFormSet,
                                             GradeCategoryForm, GradeForm)
from django_school.apps.grades.models import Grade, GradeCategory
from django_school.apps.lessons.models import Subject
from django_school.apps.users.models import ROLES

User = get_user_model()


class GradeCreateView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    SuccessMessageMixin,
    SubjectAndSchoolClassRelatedMixin,
    CreateView,
):
    model = Grade
    form_class = GradeForm
    success_message = "The grade has been added successfully."
    template_name = "grades/grade_form.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                "school_class": self.school_class,
                "subject": self.subject,
                "teacher": self.request.user,
            }
        )
        return kwargs

    def get_initial(self):
        return {
            "student": self.request.GET.get("student"),
        }

    def get_success_url(self):
        return reverse(
            "grades:class_grades",
            args=[self.kwargs["class_slug"], self.kwargs["subject_slug"]],
        )


@login_required
@roles_required(ROLES.TEACHER)
def grade_bulk_create_view(request, category_pk):
    category = get_object_or_404(
        GradeCategory.objects.select_related("subject", "school_class"), pk=category_pk
    )
    school_class = category.school_class
    subject = category.subject

    students = User.students.exclude_if_has_grade_in_category(category).filter(
        school_class=school_class
    )

    if not students:
        raise Http404

    if not does_the_teacher_teach_the_subject_to_the_class(
        request.user, subject, school_class
    ):
        raise Http404

    common_form = BulkGradeCreationCommonInfoForm(
        request.POST or None,
    )
    grades_formset = BulkGradeCreationFormSet(
        request.POST or None,
        students=students,
    )

    if request.method == "POST":
        if common_form.is_valid():
            common_data = common_form.cleaned_data
            common_data.update(
                {
                    "subject": subject,
                    "teacher": request.user,
                    "category": category,
                }
            )
            grades_formset.set_common_data(common_data=common_data)
            if grades_formset.is_valid():
                grades_formset.save()

                messages.success(request, "The grades have been added successfully.")
                return redirect(
                    reverse(
                        "grades:class_grades", args=[school_class.slug, subject.slug]
                    )
                )

    return render(
        request,
        "grades/grade_bulk_create.html",
        {
            "common_form": common_form,
            "grades_formset": grades_formset,
            "school_class": school_class,
            "subject": subject,
            "category": category,
        },
    )


class ClassGradesView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    SubjectAndSchoolClassRelatedMixin,
    TemplateView,
):
    template_name = "grades/class_grades.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "categories": GradeCategory.objects.filter(
                    subject=self.subject, school_class=self.school_class
                ).prefetch_related("grades"),
                "students": User.students.with_weighted_avg_for_subject(
                    subject=self.subject
                )
                .with_subject_grades(subject=self.subject)
                .filter(school_class=self.school_class),
            }
        )

        return context


class StudentGradesView(LoginRequiredMixin, DetailView):
    model = User
    slug_url_kwarg = "student_slug"
    template_name = "grades/student_grades.html"
    context_object_name = "student"

    def get_queryset(self):
        return User.students.visible_to_user(self.request.user).prefetch_related(
            "grades_gotten__subject", "grades_gotten__category"
        )

    def get(self, *args, **kwargs):
        # in template unseen grades are rendered in a different way
        result = super().get(*args, **kwargs)

        if self.request.user.is_parent:
            Grade.objects.filter(student__parent=self.request.user).update(
                seen_by_parent=True
            )
        elif self.request.user.is_student:
            Grade.objects.filter(student=self.request.user).update(seen_by_student=True)

        return result

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data()
        grades = self.object.grades_gotten.all()
        ctx["subjects"] = self._get_list_of_subjects(grades)
        ctx["averages"] = self._get_dict_of_averages(grades)

        return ctx

    @staticmethod
    def _get_list_of_subjects(grades):
        subjects = set()
        for grade in grades:
            subjects.add(grade.subject)

        return list(subjects)

    @staticmethod
    def _get_dict_of_averages(grades):
        averages = defaultdict(int)
        sums_of_weights = defaultdict(int)

        for grade in grades:
            averages[grade.subject.name] += grade.grade * grade.weight
            sums_of_weights[grade.subject.name] += grade.weight

        for key in averages.keys():
            averages[key] /= sums_of_weights[key]

        return dict(averages)


class SingleGradeMixin:
    model = Grade
    pk_url_kwarg = "grade_pk"
    context_object_name = "grade"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(teacher=self.request.user)
            .select_related("category", "subject", "student__school_class", "teacher")
        )

    def get_success_url(self):
        return reverse(
            "grades:class_grades",
            args=[self.object.student.school_class.slug, self.object.subject.slug],
        )


class GradeUpdateView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    SuccessMessageMixin,
    SingleGradeMixin,
    UpdateView,
):
    fields = ["grade", "weight", "comment"]
    success_message = "The grade has been updated successfully."
    template_name = "grades/grade_update.html"


class GradeDeleteView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    AjaxRequiredMixin,
    SingleGradeMixin,
    DeleteView,
):
    success_message = "The grade has been deleted successfully."
    template_name = "grades/modals/grade_delete.html"

    def delete(self, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(*args, **kwargs)


@login_required
@roles_required(ROLES.TEACHER)
def grade_categories_view(request, class_slug, subject_slug):
    school_class = get_object_or_404(Class, slug=class_slug)
    subject = get_object_or_404(Subject, slug=subject_slug)

    if not does_the_teacher_teach_the_subject_to_the_class(
        request.user, subject, school_class
    ):
        raise Http404

    if request.method == "POST":
        form = GradeCategoryForm(
            request.POST, subject=subject, school_class=school_class
        )

        if form.is_valid():
            category = form.save()
            return redirect(category.detail_url)
        else:
            return render(
                request, "grades/partials/grade_category_form.html", {"form": form}
            )

    categories = GradeCategory.objects.filter(
        subject=subject, school_class=school_class
    )
    return render(
        request,
        "grades/grade_category_list.html",
        {
            "categories": categories,
            "school_class": school_class,
            "subject": subject,
        },
    )


class GradeCategoryAccessMixin:
    def get_queryset(self):
        return super().get_queryset().select_related("school_class", "subject")

    def get_object(self, queryset=None):
        category = super().get_object(queryset)

        if not does_the_teacher_teach_the_subject_to_the_class(
            self.request.user, category.subject, category.school_class
        ):
            raise Http404

        return category


class GradeCategoryFormTemplateView(TemplateView):
    template_name = "grades/partials/grade_category_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = GradeCategoryForm(subject=None, school_class=None)

        return context


class GradeCategoryDetailView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    GradeCategoryAccessMixin,
    DetailView,
):
    model = GradeCategory
    template_name = "grades/partials/grade_category_detail.html"
    context_object_name = "category"


class GradeCategoryDeleteView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),

templates/grades/class_grades.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  {{ school_class.number }} | {{ subject.name }}
{% endblock %}


{% block content %}
  <h1>
    Class: {{ school_class.number }} <span class="mx-4 h1">|</span>
    Subject: {{ subject.name }} <span class="mx-4 h1">|</span>
    <a href="{% url "grades:categories:create" school_class.slug subject.slug %}">
      Categories
    </a>
  </h1>
  <div class="table-responsive">
    <table class="table table-bordered table-responsive" id="grades">
      <thead>
      <tr>
        <th>Student</th>
        <th style="width:10%"></th>
        {% for category in categories %}
          <th>
            {{ category.name }}
            {% if category.grades.all|length != students|length %}
              <a href="{{ category.bulk_grade_creation_url }}"
                 class="badge bg-primary text-white link-unstyled float-end">
                +
              </a>
            {% endif %}
          </th>

        {% endfor %}
        <th>
          Average
        </th>
      </tr>
      </thead>
      <tbody>
      {% for student in students %}
        <tr class="student-{{ student.pk }}">
          <td>{{ student.full_name }}</td>
          <td class="text-center">
            <a href="{% url "grades:add" class_slug subject_slug %}?student={{ student.pk }}"
               class="btn btn-outline-primary">
              +
            </a>
          </td>
          {% for category in categories %}
            <td class="category-{{ category.pk }}"></td>
          {% endfor %}

          <td>
            {% if student.w_avg %}
              {{ student.w_avg|floatformat:2 }}
            {% else %}
              -
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

{% block js %}
  <script>
      const grades = document.querySelector("#grades");

      {% for student in students %}
          {% for grade in student.subject_grades %}
              {
                  const td = grades.querySelector(`.student-{{ grade.student.pk }} .category-{{ grade.category.pk }}`);
                  td.innerText = "{{ grade.get_grade_display }}";
                  td.dataset.bsToggle = "popover";
                  td.dataset.bsContent = `
                    <h3>{{ grade.comment }}</h3>
                    <p>Weight: {{ grade.weight }}</p>
                    <a href="{{ grade.update_url }}" class="btn btn-outline-primary">Update</a>
                    <button class="btn btn-outline-danger gradeDeleteButton"
                       hx-get="{{ grade.delete_url }}"
                       hx-target="#base-modal .modal-content"
                       hx-swap="innerHTML"
                       data-bs-toggle="modal"
                       data-bs-target="#base-modal">Delete</a>
                  `;
              }
          {% endfor %}
      {% endfor %}

      bootstrap.Tooltip.Default.allowList.h1 = ["*"];
      const popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'));
      const popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
          return new bootstrap.Popover(popoverTriggerEl, {
              container: "body",
              sanitize: false,
              html: true,
          });
      });

      popoverTriggerList.forEach(function (element) {
          element.addEventListener('shown.bs.popover', function () {
              htmx.process(document.querySelector(".gradeDeleteButton"));
          });

          element.addEventListener('show.bs.popover', function (e) {
              for (const popover of popoverList) {
                  if (element !== popover._element) {
                      popover.hide();
                  }
              }
          });
      });

      document.querySelector("#base-modal").addEventListener('show.bs.modal', function () {
          popoverList.forEach(function (element) {
              element.hide();
          });
      });
  </script>
{% endblock %}

templates/grades/create_grades_in_bulk.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Add grades in bulk
{% endblock %}

{% block content %}
  <h2>Add grades in bulk | Class: {{ school_class.number }} | Subject: {{ subject.name }} | Category: {{ category.name }}</h2>

  <form method="POST">
    {{ grades_formset.management_form }}
    {{ common_form|crispy }}
    <hr>

    {% for grade_form in grades_formset %}
      <label for="{{ grade_form.grade.id_for_label }}">
        {{ grade_form.student_label }}
      </label>
      {{ grade_form|crispy }}
    {% endfor %}

    <input type="submit" value="Add" class="btn btn-success my-3">
    {% csrf_token %}
  </form>

{% endblock %}

templates/grades/grade_bulk_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Add grades in bulk
{% endblock %}

{% block content %}
  <h1>Add grades in bulk</h1>
  <h3>Class: {{ school_class.number }} | Subject: {{ subject.name }} | Category: {{ category.name }}</h3>

  <form method="POST">
    {{ grades_formset.management_form }}
    {{ common_form|crispy }}
    <hr>

    {% for grade_form in grades_formset %}
      <label for="{{ grade_form.grade.id_for_label }}">
        {{ grade_form.student_label }}
      </label>
      {{ grade_form|crispy }}
    {% endfor %}

    <input type="submit" value="Add" class="btn btn-success my-3">
    {% csrf_token %}
  </form>

{% endblock %}

templates/grades/grade_category_list.html
{% extends "base.html" %}

{% block title %}
  Grades categories | Class: {{ school_class }} | Subject: {{ subject }}
{% endblock %}

{% block content %}
  <h1>Grades categories | Class: {{ school_class }} | Subject: {{ subject }}</h1>
  <ul class="list-group my-4" id="categories">
    {% for category in categories %}
      {% include "grades/partials/grade_category_detail.html" with category=category %}
    {% endfor %}
  </ul>

  <hr>

  <button class="btn btn-primary"
          hx-get="{% url "grades:categories:form" %}"
          hx-target="#categories"
          hx-swap="beforeend">
    Add new
  </button>
{% endblock %}

templates/grades/grade_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Add grade
{% endblock %}

{% block content %}
  <h1>Add grade | Class: {{ school_class.number }} | Subject: {{ subject.name }}</h1>
  <form method="POST">
    {{ form|crispy }}

    <input type="submit" value="Add" class="btn btn-success my-3">

    {% csrf_token %}
  </form>
{% endblock %}

templates/grades/grade_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Update Grade
{% endblock %}

{% block content %}
  <h1>Update Grade | Student: {{ grade.student.full_name }} | Category: {{ grade.category.name }}</h1>
  <form method="POST">
    {{ form|crispy }}

    <input type="submit" value="Update" class="btn btn-success my-3">

    {% csrf_token %}
  </form>
{% endblock %}

templates/grades/gradecategory_list.html
{% extends "base.html" %}

{% block title %}
  Grades categories | Class: {{ school_class }} | Subject: {{ subject }}
{% endblock %}

{% block content %}
  <h1>Grades categories | Class: {{ school_class }} | Subject: {{ subject }}</h1>
  <ul class="list-group my-4" id="categories">
    {% for category in categories %}
      {% include "grades/partials/grade_category_detail.html" with category=category %}
    {% endfor %}
  </ul>

  <hr>

  <button class="btn btn-primary"
          hx-get="{% url "grades:categories:form" %}"
          hx-target="#categories"
          hx-swap="beforeend">
    Add new
  </button>
{% endblock %}

templates/grades/student_grades.html
{% extends "base.html" %}
{% load utils %}

{% block title %}
  {% if request.user == student %}
    Your Grades
  {% else %}
    {{ student.full_name }} Grades
  {% endif %}
{% endblock %}

{% block content %}
  <h1>
    {% if request.user == student %}
      Your Grades
    {% else %}
      {{ student.full_name }} Grades
    {% endif %}
  </h1>

  <div class="table-responsive">
    <table class="table table-bordered table-responsive">
      <thead>
      <tr>
        <th class="w-25">Subject</th>
        <th class="w-50">Grades</th>
        <th class="w-25">Average</th>
      </tr>
      </thead>

      <tbody>
      {% for subject in subjects %}
        <tr>
          <th>{{ subject.name }}</th>
          <td id="{{ subject.slug }}-grades">
          </td>
          <td id="{{ subject.slug }}-average"></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

{% block js %}
  <script>
      {% for grade in student.grades_gotten.all %}
          {
              const element = document.createElement("span");
              element.classList.add("pe-3");
              {% if request.user.is_student and not grade.seen_by_student %}
                  element.classList.add("text-primary");
              {% elif request.user.is_parent and not grade.seen_by_parent %}
                  element.classList.add("text-primary");
              {% endif %}

              element.dataset.bsToggle = "popover";
              element.dataset.bsContent = `
        <strong>Category:</strong> {{ grade.category.name }}<br>
        <strong>Weight:</strong> {{ grade.weight }}<br>
        <strong>Comment:</strong> {{ grade.comment|default:"-" }}<br>
        <strong>Added:</strong> {{ grade.created|date:"d-m-Y" }}
        `;
              element.innerHTML = "{{ grade.get_grade_display }}";
              document.querySelector("#{{ grade.subject.slug }}-grades").appendChild(element);
          }
      {% endfor %}

      {% for subject in subjects %}
          document.querySelector("#{{ subject.slug }}-average").innerHTML = {{ averages|get_item:subject.name|floatformat:"2" }};
      {% endfor %}


      const popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'));
      const popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
          return new bootstrap.Popover(popoverTriggerEl, {
              container: "body",
              sanitize: false,
              html: true
          });
      });

      popoverTriggerList.forEach(function (element) {
          element.addEventListener('show.bs.popover', function (e) {
              for (const popover of popoverList) {
                  if (element !== popover._element) {
                      popover.hide();
                  }
              }
          });
      });
  </script>
{% endblock %}