django_school/apps/classes/urls.py
from django.urls import path

from django_school.apps.classes.views import (ClassDetailView, ClassListView,
                                              ClassSummaryPDFView)

app_name = "classes"

urlpatterns = [
    path("", ClassListView.as_view(), name="list"),
    path("<slug:class_slug>/", ClassDetailView.as_view(), name="detail"),
    path(
        "<slug:class_slug>/summary/", ClassSummaryPDFView.as_view(), name="summary_pdf"
    ),
]

django_school/apps/events/urls.py
from django.urls import path

from django_school.apps.events.views import (EventCreateView, EventDeleteView,
                                             EventsCalendarView,
                                             EventUpdateView)

app_name = "events"

urlpatterns = [
    path("", EventsCalendarView.as_view(), name="calendar"),
    path("create/", EventCreateView.as_view(), name="create"),
    path("update/<int:event_pk>/", EventUpdateView.as_view(), name="update"),
    path("delete/<int:event_pk>/", EventDeleteView.as_view(), name="delete"),
]

django_school/apps/lessons/urls.py
from django.urls import path

from django_school.apps.lessons.views import (ClassSubjectListView,
                                              ClassTimetableView,
                                              HomeworkDetailView,
                                              HomeworkListView,
                                              LessonSessionListView,
                                              SetHomeworkView,
                                              TeacherTimetableView,
                                              class_attendance_summary_view,
                                              lesson_session_detail_view,
                                              student_attendance_summary_view,
                                              submit_homework_realisation_view,
                                              timetable_list_view)

app_name = "lessons"

urlpatterns = [
    path("timetables/", timetable_list_view, name="timetables_list"),
    path(
        "class_timetable/<slug:class_slug>/",
        ClassTimetableView.as_view(),
        name="class_timetable",
    ),
    path(
        "teacher_timetable/<slug:teacher_slug>/",
        TeacherTimetableView.as_view(),
        name="teacher_timetable",
    ),
    path(
        "sessions/",
        LessonSessionListView.as_view(),
        name="session_list",
    ),
    path(
        "sessions/<int:session_pk>/",
        lesson_session_detail_view,
        name="session_detail",
    ),
    path(
        "subjects/<slug:class_slug>/",
        ClassSubjectListView.as_view(),
        name="class_subject_list",
    ),
    path(
        "attendance/student/<slug:student_slug>/",
        student_attendance_summary_view,
        name="student_attendance",
    ),
    path(
        "attendance/class/<slug:class_slug>/",
        class_attendance_summary_view,
        name="class_attendance",
    ),
    path(
        "<slug:class_slug>/<slug:subject_slug>/set_homework/",
        SetHomeworkView.as_view(),
        name="set_homework",
    ),
    path("homeworks/", HomeworkListView.as_view(), name="homework_list"),
    path(
        "homeworks/<int:homework_pk>/",
        HomeworkDetailView.as_view(),
        name="homework_detail",
    ),
    path(
        "homeworks/<int:homework_pk>/submit_realisation/",
        submit_homework_realisation_view,
        name="submit_homework_realisation",
    ),
]

django_school/apps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from django_school.apps.users.views import (NoteCreateView, NoteDeleteView,
                                            NoteListView,
                                            PasswordChangeWithMessageView,
                                            SetPasswordView, StudentDetailView)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeWithMessageView.as_view(),
        name="password_change",
    ),
    path(
        "password_set/<uidb64>/<token>/", SetPasswordView.as_view(), name="password_set"
    ),
    path(
        "notes/add/",
        NoteCreateView.as_view(),
        name="add_note",
    ),
    path("notes/<int:note_pk>/delete/", NoteDeleteView.as_view(), name="note_delete"),
    path("notes/", NoteListView.as_view(), name="note_list"),
    path("<slug:student_slug>/", StudentDetailView.as_view(), name="detail"),
]

django_school/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django_school.apps.common.views import attached_file_delete_view, index

urlpatterns = [
    path("", index, name="index"),
    path("users/", include("django_school.apps.users.urls", namespace="users")),
    path("classes/", include("django_school.apps.classes.urls", namespace="classes")),
    path("lessons/", include("django_school.apps.lessons.urls", namespace="lessons")),
    path("grades/", include("django_school.apps.grades.urls", namespace="grades")),
    path(
        "messages/", include("django_school.apps.messages.urls", namespace="messages")
    ),
    path("events/", include("django_school.apps.events.urls", namespace="events")),
    path("admin/", admin.site.urls),
    path("martor/", include("martor.urls")),
    path(
        "attached_files/<int:pk>/delete/",
        attached_file_delete_view,
        name="attached_file_delete",
    ),
    path("__debug__", include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  {% block css %}
  {% endblock %}

  <title>{% block title %}School Management System{% endblock %}</title>
</head>
<body>
  <header class="header">
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="{% url "index" %}">
        <img src="{% static "images/crest.svg" %}" alt="Hogwarts Crest" id="hogwarts-crest">
          Hogwarts School
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <a class="nav-link" href="{% url "lessons:timetables_list" %}">Timetables</a>
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url "events:calendar" %}">
              Events {% if unseen_events_count != 0 %}({{ unseen_events_count }}){% endif %}
            </a>
            {% if request.user.is_teacher %}
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="teachingDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  Teaching
                </a>
                <div class="dropdown-menu" aria-labelledby="teachingDropdown">
                  <a class="dropdown-item" href="{% url "classes:list" %}">Classes</a>
                  <a class="dropdown-item" href="{% url "lessons:session_list" %}">Lesson Sessions</a>
                  <a class="dropdown-item" href="{% url "lessons:homework_list" %}">Homeworks</a>
                  {% if request.user.is_teacher %}
                    <a class="dropdown-item" href="{{ request.user.teacher_class.detail_url }}">Your class</a>
                  {% endif %}
                </div>
              </div>
            {% elif request.user.is_student %}
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="learningDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                  {% with notification_count=unseen_grades_count|add:unseen_notes_count %}
                    Learning {% if notification_count != 0 %}({{ notification_count }}){% endif %}
                  {% endwith %}
                </a>
                <div class="dropdown-menu" aria-labelledby="learningDropdown">
                  <a class="dropdown-item" href="{{ request.user.grades_url }}">
                    Grades {% if unseen_grades_count != 0 %}({{ unseen_grades_count }}){% endif %}
                  </a>
                  <a class="dropdown-item" href="{{ request.user.attendance_url }}">Attendance</a>
                  <a class="dropdown-item" href="{% url "lessons:session_list" %}">Lesson Sessions</a>
                  <a class="dropdown-item" href="{% url "lessons:homework_list" %}">Homeworks</a>
                  <a class="dropdown-item" href="{% url "users:note_list" %}">
                    Notes {% if unseen_notes_count != 0 %}({{ unseen_notes_count }}){% endif %}
                  </a>
                </div>
              </div>
            {% elif request.user.is_parent %}
              <a class="nav-link" href="{{ request.user.grades_url }}">
                Grades {% if unseen_grades_count != 0 %}({{ unseen_grades_count }}){% endif %}
              </a>
              <a class="nav-link" href="{{ request.user.attendance_url }}">Attendance</a>
              <a class="nav-link" href="{% url "users:note_list" %}">
                Notes {% if unseen_notes_count != 0 %}({{ unseen_notes_count }}){% endif %}
              </a>
            {% endif %}
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-bs-toggle="dropdown"
                 aria-expanded="false">
                Messages {% if unread_messages_count != 0 %}({{ unread_messages_count }}) {% endif %}
              </a>
              <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                <a class="dropdown-item" href="{% url "messages:received" %}">Received</a>
                <a class="dropdown-item" href="{% url "messages:sent" %}">Sent</a>
                <a class="dropdown-item" href="{% url "messages:send" %}">Send</a>
              </div>
            </div>


            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button" data-bs-toggle="dropdown"
                 aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="accountDropdown">
                <a class="dropdown-item" href="{% url "users:password_change" %}">Change Password</a>
                <a class="dropdown-item" href="{% url "users:logout" %}">Logout</a>
              </div>
            </div>
          {% else %}
            <a class="nav-link" href="{% url "users:login" %}">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>
    </div>
  </header>
  <div class="container">
  {% if messages %}
    <div id="messages" class="mt-3">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <main class="py-3 px-3">
    {% block content %}{% endblock %}
  </main>

  <div class="modal fade" id="base-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/htmx.org@1.5.0"
        integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI"
        crossorigin="anonymous"></script>

<script>
    document.addEventListener("htmx:configRequest", e => {
        e.detail.headers["X-CSRFToken"] = "{{ csrf_token }}"
    });
</script>

{% block js %}{% endblock %}

</body>
</html>

templates/base_modal.html
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">
    {% block title %}{% endblock %}
  </h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <form id="modal-form" method="post" enctype="multipart/form-data" action="{{ request.get_full_path }}">
    {% block body %}{% endblock %}
    {% csrf_token %}
  </form>
</div>
<div class="modal-footer">
  {% block footer %}
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary" form="modal-form">Confirm</button>
  {% endblock %}
</div>