django_school/apps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from django_school.apps.users.views import (NoteCreateView, NoteDeleteView,
                                            NoteListView,
                                            PasswordChangeWithMessageView,
                                            SetPasswordView, StudentDetailView)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeWithMessageView.as_view(),
        name="password_change",
    ),
    path(
        "password_set/<uidb64>/<token>/", SetPasswordView.as_view(), name="password_set"
    ),
    path(
        "notes/add/",
        NoteCreateView.as_view(),
        name="add_note",
    ),
    path("notes/<int:note_pk>/delete/", NoteDeleteView.as_view(), name="note_delete"),
    path("notes/", NoteListView.as_view(), name="note_list"),
    path("<slug:student_slug>/", StudentDetailView.as_view(), name="detail"),
]

django_school/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django_school.apps.common.views import attached_file_delete_view, index

urlpatterns = [
    path("", index, name="index"),
    path("users/", include("django_school.apps.users.urls", namespace="users")),
    path("classes/", include("django_school.apps.classes.urls", namespace="classes")),
    path("lessons/", include("django_school.apps.lessons.urls", namespace="lessons")),
    path("grades/", include("django_school.apps.grades.urls", namespace="grades")),
    path(
        "messages/", include("django_school.apps.messages.urls", namespace="messages")
    ),
    path("events/", include("django_school.apps.events.urls", namespace="events")),
    path("admin/", admin.site.urls),
    path("martor/", include("martor.urls")),
    path(
        "attached_files/<int:pk>/delete/",
        attached_file_delete_view,
        name="attached_file_delete",
    ),
    path("__debug__", include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/apps/users/models.py
from django.apps import apps
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Count, F, Prefetch, Q, Sum
from django.urls import reverse
from django.utils.text import slugify

from django_school.apps.classes.models import Class
from django_school.apps.common.models import Address
from django_school.apps.grades.models import Grade


class StudentsQuerySet(models.QuerySet):
    def with_weighted_avg_for_subject(self, subject):
        return self.annotate(
            w_avg=Sum(
                F("grades_gotten__grade") * F("grades_gotten__weight"),
                filter=Q(grades_gotten__subject=subject),
            )
            / Sum(F("grades_gotten__weight"), filter=Q(grades_gotten__subject=subject)),
        )

    def with_subject_grades(self, subject):
        return self.prefetch_related(
            Prefetch(
                "grades_gotten",
                queryset=Grade.objects.filter(subject=subject).select_related(
                    "category"
                ),
                to_attr="subject_grades",
            )
        )

    def with_attendance(self, **attendance_params):
        statuses = ["present", "absent", "exempt", "excused"]
        counters = {
            f"{status}_hours": Count(
                "attendance",
                filter=Q(attendance__status=status, **attendance_params),
                distinct=True,
            )
            for status in statuses
        }

        return self.annotate(
            total_attendance=Count(
                "attendance",
                ~Q(attendance__status="none") & Q(**attendance_params),
                distinct=True,
            ),
            **counters,
        )

    def with_homework_realisations(self, homework):
        return (
            self.filter(school_class_id=homework.school_class_id)
            .prefetch_related(
                Prefetch(
                    "homeworks_realisations",
                    queryset=apps.get_model("lessons", "HomeworkRealisation")
                    .objects.filter(homework=homework)
                    .prefetch_related("attached_files"),
                    to_attr="realisation",
                )
            )
            .distinct()
        )

    def with_teacher_notes(self, teacher):
        return self.prefetch_related(
            Prefetch("notes_gotten", queryset=Note.objects.filter(teacher=teacher))
        )

    def exclude_if_has_grade_in_category(self, category):
        return self.annotate(
            has_grade=Count("grades_gotten", filter=Q(grades_gotten__category=category))
        ).exclude(has_grade=1)

    def visible_to_user(self, user):
        if user.is_teacher:
            return self.filter(school_class__lessons__teacher=user).distinct()
        elif user.is_student:
            return self.filter(pk=user.pk)
        elif user.is_parent:
            return self.filter(pk=user.child_id)


class StudentsManager(models.Manager):
    def get_queryset(self):
        return StudentsQuerySet(self.model, using=self._db).filter(role=ROLES.STUDENT)


class TeachersManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=ROLES.TEACHER)


class CustomUserManager(UserManager):
    def get(self, *args, **kwargs):
        return (
            super()
            .select_related("child__school_class", "school_class", "teacher_class")
            .get(*args, **kwargs)
        )


class ROLES(models.TextChoices):
    TEACHER = ("TEACHER", "Teacher")
    STUDENT = ("STUDENT", "Student")
    PARENT = ("PARENT", "Parent")


class User(AbstractUser):
    GENDER_CHOICES = [
        ("male", "male"),
        ("female", "female"),
        ("other", "other"),
    ]

    role = models.TextField(null=True, choices=ROLES.choices)
    slug = models.SlugField(max_length=64, unique=True)
    personal_id = models.CharField(max_length=16, null=True, blank=True)
    phone_number = models.CharField(max_length=16, null=True, blank=True)
    gender = models.CharField(
        max_length=16, choices=GENDER_CHOICES, null=True, blank=True
    )
    address = models.OneToOneField(Address, models.SET_NULL, null=True, blank=True)
    school_class = models.ForeignKey(
        Class, models.SET_NULL, null=True, blank=True, related_name="students"
    )
    child = models.OneToOneField(
        "self", models.SET_NULL, null=True, blank=True, related_name="parent"
    )

    objects = CustomUserManager()
    students = StudentsManager.from_queryset(StudentsQuerySet)()
    teachers = TeachersManager()

    def __str__(self):
        return self.full_name

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.full_name)
        super().save(**kwargs)

    def clean(self):
        super().clean()

        if not self.is_student and self.school_class is not None:
            raise ValidationError("A class can be assigned only to a student")

        if not self.is_parent and self.child is not None:
            raise ValidationError("A child can be assigned only to a parent")
        elif self.child and not self.child.is_student:
            raise ValidationError("A child must be a student")

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def is_teacher(self):
        return self.role == ROLES.TEACHER

    @property
    def is_student(self):
        return self.role == ROLES.STUDENT

    @property
    def is_parent(self):
        return self.role == ROLES.PARENT

    @property
    def is_tutor(self):
        return bool(getattr(self, "teacher_class", False))

    @property
    def student_detail_url(self):
        return reverse("users:detail", args=[self.slug])

    @property
    def attendance_url(self):
        if self.is_student:
            return reverse("lessons:student_attendance", args=[self.slug])
        elif self.is_parent:
            return reverse("lessons:student_attendance", args=[self.child.slug])

    @property
    def teacher_timetable_url(self):
        return reverse("lessons:teacher_timetable", args=[self.slug])

    @property
    def grades_url(self):
        if self.is_student:
            return reverse("grades:student_grades", args=[self.slug])
        elif self.is_parent:
            return reverse("grades:student_grades", args=[self.child.slug])


class NoteQuerySet(models.QuerySet):
    def visible_to_user(self, user):
        if user.is_teacher:
            return self.filter(teacher=user)
        elif user.is_student:
            return self.filter(student=user)
        elif user.is_parent:
            return self.filter(student__parent=user)


class Note(models.Model):
    note = models.CharField(max_length=128)
    created = models.DateTimeField(auto_now_add=True)
    student = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notes_gotten"
    )
    teacher = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notes_given"
    )
    seen_by_student = models.BooleanField(default=False)
    seen_by_parent = models.BooleanField(default=False)

    objects = NoteQuerySet.as_manager()

    def __str__(self):
        return self.note

    @property
    def delete_url(self):
        return reverse("users:note_delete", args=[self.pk])

django_school/apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import SetPasswordForm, UserCreationForm

from django_school.apps.users.models import Note

User = get_user_model()


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["note", "student"]

    def __init__(self, *args, **kwargs):
        self.teacher = kwargs.pop("teacher")

        super().__init__(*args, **kwargs)

        self.fields["student"].queryset = User.students.visible_to_user(self.teacher)

    def is_valid(self):
        self.instance.teacher = self.teacher

        return super().is_valid()


class UserCreationWithoutPasswordForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].required = False
        self.fields["password2"].required = False


class SetPasswordWithActivationForm(SetPasswordForm):
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = True

        if commit:
            user.save()

        return user

django_school/apps/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetConfirmView)
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from django_school.apps.common.utils import (AjaxRequiredMixin,
                                             RolesRequiredMixin)
from django_school.apps.users.forms import (NoteForm,
                                            SetPasswordWithActivationForm)
from django_school.apps.users.models import ROLES, Note
from django_school.apps.users.token_generator import \
    set_password_token_generator

User = get_user_model()


class StudentDetailView(
    LoginRequiredMixin, RolesRequiredMixin(ROLES.TEACHER), DetailView
):
    model = User
    slug_url_kwarg = "student_slug"
    template_name = "users/student_detail.html"
    context_object_name = "student"

    def dispatch(self, request, *args, **kwargs):
        if self.is_requested_user_role_is_teacher():
            raise Http404()

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return (
            User.students.visible_to_user(self.request.user)
            .with_teacher_notes(self.request.user)
            .select_related("address", "school_class__tutor")
        )

    def is_requested_user_role_is_teacher(self):
        return User.objects.filter(
            slug=self.kwargs[self.slug_url_kwarg], role=ROLES.TEACHER
        ).exists()


class PasswordChangeWithMessageView(SuccessMessageMixin, PasswordChangeView):
    success_url = reverse_lazy("index")
    success_message = "The password has been changed successfully."


class SetPasswordView(SuccessMessageMixin, PasswordResetConfirmView):
    token_generator = set_password_token_generator
    form_class = SetPasswordWithActivationForm
    template_name = "registration/password_change_form.html"
    success_url = reverse_lazy("users:login")
    success_message = "The password has been set successfully"


class NoteCreateView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    SuccessMessageMixin,
    CreateView,
):
    model = Note
    form_class = NoteForm
    success_message = "The note has been created successfully"
    template_name = "users/note_create.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"teacher": self.request.user})

        return kwargs

    def get_initial(self):
        return {"student": self.request.GET.get("student")}

    def get_success_url(self):
        return self.object.student.student_detail_url


class NoteDeleteView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    AjaxRequiredMixin,
    DeleteView,
):
    model = Note
    pk_url_kwarg = "note_pk"
    template_name = "users/modals/note_delete.html"
    context_object_name = "note"

    def get_queryset(self):
        return super().get_queryset().visible_to_user(user=self.request.user)

    def get_success_url(self):
        return self.object.student.student_detail_url


class NoteListView(
    LoginRequiredMixin, RolesRequiredMixin(ROLES.STUDENT, ROLES.PARENT), ListView
):
    model = Note
    paginate_by = 10
    ordering = ["-created"]
    template_name = "users/note_list.html"
    context_object_name = "notes"

    def get(self, *args, **kwargs):
        # in template unseen grades are rendered in a different way
        result = super().get(*args, **kwargs)

        if self.request.user.is_parent:
            Note.objects.filter(student__parent=self.request.user).update(
                seen_by_parent=True
            )
        elif self.request.user.is_student:
            Note.objects.filter(student=self.request.user).update(seen_by_student=True)

        return result

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .visible_to_user(user=self.request.user)
            .select_related("teacher")
        )

templates/users/note_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Add note
{% endblock %}

{% block content %}
  <h1>Add note</h1>

  <form method="POST">
    {{ form|crispy }}

    {% csrf_token %}

    <input type="submit" value="Add" class="btn btn-primary">
  </form>
{% endblock %}

templates/users/note_list.html
{% extends "base.html" %}

{% block title %}
  Notes
{% endblock %}

{% block content %}
  <h1>
    {% if request.user.is_student %}
      Your notes
    {% else %}
      Your child's notes
    {% endif %}
  </h1>

  <ul class="list-group">
    {% for note in notes %}
      <li class="list-group-item">
        <strong>Note:</strong> {{ note.note }}<br>
        <strong>Teacher:</strong> {{ note.teacher.full_name }}<br>
        <strong>Created:</strong> {{ note.created }}
      </li>
    {% empty %}
      <p>
      {% if request.user.is_student %}
        You have not received any notes yet.
      {% else %}
        Your child has not received any notes yet.
      {% endif %}
      </p>
    {% endfor %}
  </ul>

   {% include "common/paginator.html" %}
{% endblock %}

templates/users/student_detail.html
{% extends "base.html" %}

{% block title %}
  Profile | {{ user.full_name }}
{% endblock %}

{% block content %}
  <h1>Personal Information:</h1>
  <ul id="personal-info">
    <li><strong>Full name</strong>: {{ student.full_name }}</li>
    {% with class=student.school_class %}
      <li><strong>Class</strong>: <a href="{{ class.detail_url }}">
        {{ class.number }}
      </a></li>
      <li><strong>Tutor</strong>: {{ class.tutor.full_name }}</li>
    {% endwith %}
    <li><strong>Last Login</strong>: {{ student.last_login }}</li>
    <li><strong>Email</strong>: {{ student.email }}</li>
    <li><strong>Phone number</strong>: {{ student.phone_number }}</li>
    <li><strong>Address</strong>: {{ student.address }}</li>
  </ul>

  <hr>
  <h1>Notes:</h1>
  <ul class="list-group">
    {% for note in student.notes_gotten.all %}
      <li class="list-group-item">
        <span class="h3">{{ note.note }}</span>

        <button type="button"
            class="btn btn-danger float-end"
            hx-get="{{ note.delete_url }}"
            hx-target="#base-modal .modal-content"
            hx-swap="innerHTML"
            data-bs-toggle="modal"
            data-bs-target="#base-modal">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"#}
             viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd"
                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </button>
      </li>
    {% empty %}
      <p>The student has not received any note yet.</p>
    {% endfor %}
  </ul>

  <a class="btn btn-primary mt-3" href="{% url "users:add_note" %}?student={{ student.pk }}">Add note</a>
{% endblock %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block title %}
  Profile | {{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block content %}
  <h1>Personal Information</h1>
  <ul id="personal-info">
    <li><strong>Full name</strong>: {{ user.first_name }} {{ user.last_name }}</li>
    {% with class=user.school_class %}
      {% if class %}
        <li><strong>Class</strong>: <a href="{{ class.get_absolute_url }}">
          {{ class.number }}
        </a></li>
        <li><strong>Tutor</strong>: <a href="{{ class.tutor.get_absolute_url }}">
          {{ class.tutor.first_name }} {{ class.tutor.last_name }}
        </a></li>
      {% endif %}
    {% endwith %}
    <li><strong>Last Login</strong>: {{ user.last_login }}</li>
    <li><strong>Email</strong>: {{ user.email }}</li>
    <li><strong>Phone number</strong>: {{ user.phone_number }}</li>
    <li><strong>Address</strong>: {{ user.address }}</li>
  </ul>
{% endblock %}