django_school/apps/events/urls.py
from django.urls import path

from django_school.apps.events.views import (EventCreateView, EventDeleteView,
                                             EventsCalendarView,
                                             EventUpdateView)

app_name = "events"

urlpatterns = [
    path("", EventsCalendarView.as_view(), name="calendar"),
    path("create/", EventCreateView.as_view(), name="create"),
    path("update/<int:event_pk>/", EventUpdateView.as_view(), name="update"),
    path("delete/<int:event_pk>/", EventDeleteView.as_view(), name="delete"),
]

django_school/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django_school.apps.common.views import attached_file_delete_view, index

urlpatterns = [
    path("", index, name="index"),
    path("users/", include("django_school.apps.users.urls", namespace="users")),
    path("classes/", include("django_school.apps.classes.urls", namespace="classes")),
    path("lessons/", include("django_school.apps.lessons.urls", namespace="lessons")),
    path("grades/", include("django_school.apps.grades.urls", namespace="grades")),
    path(
        "messages/", include("django_school.apps.messages.urls", namespace="messages")
    ),
    path("events/", include("django_school.apps.events.urls", namespace="events")),
    path("admin/", admin.site.urls),
    path("martor/", include("martor.urls")),
    path(
        "attached_files/<int:pk>/delete/",
        attached_file_delete_view,
        name="attached_file_delete",
    ),
    path("__debug__", include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/apps/events/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Prefetch, Q
from django.urls import reverse
from django.utils import timezone

from django_school.apps.classes.models import Class

User = get_user_model()


class EventQuerySet(models.QuerySet):
    def for_year_and_month(self, year, month):
        return self.filter(date__year=year, date__month=month)

    def visible_to_user(self, user):
        global_events = Q(school_class=None)

        if user.is_teacher:
            return self.filter(global_events | Q(teacher=user))
        elif user.is_student:
            return self.filter(global_events | Q(school_class_id=user.school_class_id))
        elif user.is_parent:
            return self.filter(
                global_events | Q(school_class_id=user.child.school_class_id)
            )

    def with_statuses(self, user):
        qs = self.prefetch_related(
            Prefetch(
                "statuses",
                queryset=EventStatus.objects.filter(user=user),
                to_attr="status",
            )
        )

        return qs


class Event(models.Model):
    title = models.CharField(max_length=32)
    description = models.TextField(max_length=256, blank=True, null=True)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="created_events",
    )
    # if none, the event is global
    school_class = models.ForeignKey(
        Class,
        on_delete=models.SET_NULL,
        related_name="events",
        blank=True,
        null=True,
    )

    objects = EventQuerySet.as_manager()

    def clean(self):
        super().clean()

        if self.date < timezone.now().date():
            raise ValidationError("The date must be in the future.")

        if not self.teacher.is_teacher:
            raise ValidationError("Teacher is not a teacher.")

    @property
    def is_global(self):
        return self.school_class is None

    @property
    def update_url(self):
        return reverse("events:update", args=[self.pk])

    @property
    def delete_url(self):
        return reverse("events:delete", args=[self.pk])


class EventStatusManager(models.Manager):
    def create_multiple(self, event):
        users_qs = (
            User.objects.filter(
                Q(school_class_id=event.school_class_id)
                | Q(child__school_class_id=event.school_class_id)
            )
            if event.school_class
            else User.objects.exclude(pk=event.teacher_id)
        )
        statuses = [EventStatus(event=event, user=user) for user in users_qs]
        self.model.objects.bulk_create(statuses)

        return statuses


class EventStatus(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="statuses")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    seen = models.BooleanField(default=False)

    objects = EventStatusManager()

django_school/apps/events/forms.py
from django import forms

from django_school.apps.classes.models import Class
from django_school.apps.events.models import Event, EventStatus


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ("created", "teacher")
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

        self.fields["school_class"].queryset = Class.objects.visible_to_user(self.user)

    def is_valid(self):
        self.instance.teacher = self.user
        return super().is_valid()

    def save(self, commit=True):
        event = super().save(commit=False)

        if commit:
            event.save()
            EventStatus.objects.create_multiple(event)

        return event

django_school/apps/events/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, TemplateView,
                                  UpdateView)

from django_school.apps.common.utils import (AjaxRequiredMixin,
                                             RolesRequiredMixin)
from django_school.apps.events.calendar import EventCalendar
from django_school.apps.events.forms import EventForm
from django_school.apps.events.models import Event, EventStatus
from django_school.apps.users.models import ROLES


class EventsCalendarView(LoginRequiredMixin, TemplateView):
    template_name = "events/events.html"

    def get(self, *args, **kwargs):
        result = super().get(
            *args, **kwargs
        )  # unseen events are rendered in a different way

        year, month = self.get_year_and_month()
        EventStatus.objects.filter(
            user=self.request.user, event__date__year=year, event__date__month=month
        ).update(seen=True)

        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year, month = self.get_year_and_month()
        events = (
            Event.objects.for_year_and_month(year, month)
            .visible_to_user(self.request.user)
            .with_statuses(self.request.user)
            .select_related("school_class", "teacher")
        )
        calendar = EventCalendar(events, user=self.request.user).formatmonth(
            year, month
        )

        context.update(
            {
                "calendar": calendar,
                "year": year,
                "month": month,
            }
        )

        return context

    def get_year_and_month(self):
        today = datetime.date.today()

        try:
            year = int(self.request.GET["year"])
            month = int(self.request.GET["month"])
        except (ValueError, KeyError):
            year = today.year
            month = today.month

        if month > 12:
            year += 1
            month = 1
        elif month < 1:
            year -= 1
            month = 12

        return year, month


class EventCreateView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    SuccessMessageMixin,
    CreateView,
):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy("events:calendar")
    success_message = "The event has been created successfully"
    template_name = "events/event_form.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs


class EventUpdateView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    SuccessMessageMixin,
    UpdateView,
):
    model = Event
    form_class = EventForm
    pk_url_kwarg = "event_pk"
    success_url = reverse_lazy("events:calendar")
    success_message = "The event has been updated successfully"
    template_name = "events/event_update.html"
    context_object_name = "event"

    def get_queryset(self):
        return super().get_queryset().filter(teacher=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs


class EventDeleteView(
    LoginRequiredMixin,
    RolesRequiredMixin(ROLES.TEACHER),
    AjaxRequiredMixin,
    DeleteView,
):
    model = Event
    pk_url_kwarg = "event_pk"
    success_url = reverse_lazy("events:calendar")
    success_message = "The event has been deleted successfully."
    template_name = "events/modals/event_delete.html"
    context_object_name = "event"

    def get_queryset(self):
        return super().get_queryset().filter(teacher=self.request.user)

    def delete(self, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(*args, **kwargs)

templates/events/event.html
<div class="text-white p-1 my-1 rounded event
            {% if not event.status.0.seen and not user.is_teacher %}
              bg-warning
            {% elif event.school_class %}
              bg-primary
            {% else %}
              bg-danger
            {% endif %}"
     data-bs-toggle="popover" title="{{ event.title }}"
     data-bs-content="<strong>Description: </strong>{% if event.description %}{{ event.description }}{% endif %}<br>
                      <strong>Created: </strong> {{ event.created }}<br>
                      <strong>Teacher: </strong> {{ event.teacher.full_name }}<br>
                      <strong>Scope:</strong>
             {% if event.school_class %}{{ event.school_class }}{% else %}global{% endif %}<br>
                      {% if user == event.teacher %}<a href='{{ event.update_url }}' class='btn btn-outline-primary'>Update</a>
                      <button
                        class='btn btn-outline-danger eventDeleteButton'
                        hx-get='{{ event.delete_url }}'
                        hx-target='#base-modal .modal-content'
                        hx-swap='innerHTML'
                        data-bs-toggle='modal'
                        data-bs-target='#base-modal'>
                          Delete
                       </button>{% endif %}">
  {{ event.title }}
</div>

templates/events/event_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Add event
{% endblock %}

{% block content %}
  <h1>Add event</h1>
  <form method="POST">
    {{ form|crispy }}

    <input type="submit" value="Create" class="btn btn-success my-3">

    {% csrf_token %}
  </form>
{% endblock %}

templates/events/event_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  Update event "{{ event.title }}"
{% endblock %}

{% block content %}
  <h1>Update event "{{ event.title }}"</h1>
  <form method="POST">
    {{ form|crispy }}

    <input type="submit" value="Create" class="btn btn-success my-3">

    {% csrf_token %}
  </form>
{% endblock %}

templates/events/events.html
{% extends "base.html" %}

{% block title %}
  Events
{% endblock title %}

{% block content %}
  <h1>Events</h1>

  <div class="mb-2">
    <button class="btn btn-primary p-0" hx-target="body"
            hx-swap="outerHTML" hx-get="{% url "events:calendar" %}?year={{ year }}&month={{ month|add:"-1" }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left-short"
           viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z"/>
      </svg>
    </button>

    <button class="btn btn-primary p-0" hx-target="body"
            hx-swap="outerHTML" hx-get="{% url "events:calendar" %}?year={{ year }}&month={{ month|add:"1" }}">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-right-short"
           viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
      </svg>
    </button>


    {% if request.user.is_teacher %}
      <a href="{% url "events:create" %}">
        <button class="btn btn-primary float-end">
          Create
        </button>
      </a>
    {% endif %}
  </div>

  <div class="table-responsive" id="calendar">
    {{ calendar|safe }}
  </div>


{% endblock content %}

{% block js %}
  <script>
      const popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'));
      const popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
          return new bootstrap.Popover(popoverTriggerEl, {
              container: "body",
              sanitize: false,
              html: true,
          });
      });

      popoverTriggerList.forEach(function (element) {
          element.addEventListener('shown.bs.popover', function (e) {
              htmx.process(document.querySelector(".eventDeleteButton"));


          });

          element.addEventListener('show.bs.popover', function (e) {
              for(const popover of popoverList) {
                  if (element !== popover._element) {
                      popover.hide();
                  }
              }
          });
      });

      document.querySelector("#base-modal").addEventListener('show.bs.modal', function () {
          popoverList.forEach(function (element) {
              element.hide()
          });
      });

  </script>
{% endblock %}